### ISSUE TITLE
Bug: Website header incorrect Discord and Github links

### ISSUE THREAD

**Issue by data-niklas** [pulse-browser/website#5]
## Description
The Github icon redirects to the Discord link and the Discord icon redirects to Github

## Reproducing
1. Go to [Pulsebrowser.app](https://pulsebrowser.app/)
2. Click on either the Github or Discord icon in the header

## Source code
https://github.com/pulse-browser/website/blob/6b579ca54ca6816441e13bf3f26b7433d717eab1/components/nav/index.tsx#L27
https://github.com/pulse-browser/website/blob/6b579ca54ca6816441e13bf3f26b7433d717eab1/components/nav/index.tsx#L30-L36

**Comment by data-niklas** [comment]
This has been really confusing

**Comment by trickypr** [comment]
Oops, I updated the icons and must have gotten them in the wrong order. Thanks for the issue
