### ISSUE TITLE
User welcome page

### ISSUE THREAD

**Issue by PressJump** [pulse-browser/website#6]
Firefox has multiple bookmarks for different types of pages that may be useful to the user. It may be a good idea for a future update to add a user welcome page detailing the features Pulse Browser provides and pages that may help them on the website. Making it easier for the user to find things in one all together hub.

**Comment by trickypr** [comment]
**Opinion:** I despise those bookmarks. They should be removed and we should not provide a replacement.

**Comment by PressJump** [comment]
More than fair enough @trickypr .
